// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAJovz5EHM3z8SdBmPQcrJCCaXVx-htXI',
    appId: '1:777099756390:android:92a5b19f5185581d24fea7',
    messagingSenderId: '777099756390',
    projectId: 'flutter-project-tek',
    storageBucket: 'flutter-project-tek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiML0Slnv6qrUgETyWPQQTEg8Gws57CNo',
    appId: '1:777099756390:ios:82b26e816956f8a824fea7',
    messagingSenderId: '777099756390',
    projectId: 'flutter-project-tek',
    storageBucket: 'flutter-project-tek.appspot.com',
    iosClientId: '777099756390-hcfhq0c6bvmvp69atv6geeo2kim1ncnm.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.app',
  );
}
